---
name: "Image Build Push"

on:
  push:
    branches:
      - main

env:
  PROJECT_NUMBER: 623372444441
  PROJECT_ID: cloudrun-handson-461709
  WIF_POOL_ID: github-actions-pool
  WIF_POOL_PROVIDER_ID: github-actions-pool-provider
  SERVICE_ACCOUNT: github-actions-sa@cloudrun-handson-461709.iam.gserviceaccount.com

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          token_format: "access_token"
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.WIF_POOL_ID }}/providers/${{ env.WIF_POOL_PROVIDER_ID }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Use gcloud cli
        run: gcloud info
